# MIT License

# Copyright (c) 2021 ByteDance Inc. All rights reserved.
# Copyright (c) 2021 Duke University. All rights reserved.

# See LICENSE for license information

import time
import space
import subprocess
import logger


# Out-of-band TCP ports handed to the engine.  Kept inside the ephemeral range
# but walked monotonically (see _next_port) so that a port is never reused while
# the previous point's socket is still in TIME_WAIT.
kPortBase = 20000
kPortTop = 60000


class Engine(object):
    # @binary: the absolute path of the traffic_engine
    def __init__(self, binary, ip_to_host={}):
        super(Engine).__init__()
        self._binary = binary
        self._global_port = kPortBase
        self._base_port = kPortBase   # first port used by the current point
        self._commands = {}
        self._ip_to_host = ip_to_host
        self._scripts_path = "/tmp/collie-scripts/"
        cmd = "rm -rf {}".format(self._scripts_path)
        print (cmd)
        subprocess.check_output(cmd, shell=True)
        cmd = "mkdir -p {}".format(self._scripts_path)
        print (cmd)
        subprocess.check_output(cmd, shell=True)

    def _next_port(self):
        port = self._global_port
        self._global_port += 1
        if self._global_port >= kPortTop:
            self._global_port = kPortBase
        return port
    # translate Point in search space into the params to set up traffic engine

    # return the number of RTS queue pairs generated by Collie.
    def check_run(self, expected_n):
        cmd = "rdma res show qp | grep 'RTS.*collie_engine' | wc -l"
        for i in range(10):
            try:
                ret = int(subprocess.check_output(
                    cmd, shell=True).decode().rstrip('\n'))
                if ret == expected_n:
                    return 0
            except Exception as e:
                print(e)
                return -1
            time.sleep(1)
        return -1

    def translate(self, point: space.Point, base_port=None):
        # @base_port: replay a previous point on exactly the ports it used.
        #             log_scripts() passes it so the reproduce script matches
        #             the run that was actually measured; upstream got this for
        #             free by resetting the port counter to 3000 every time,
        #             which also meant every point fought the previous point's
        #             TIME_WAIT sockets.
        self.clean()
        if base_port is None:
            self._base_port = self._global_port
        else:
            self._global_port = int(base_port)
            self._base_port = int(base_port)
        for traffic in point._traffics:
            server = traffic.get_server()
            server_ip = server.get_ip()
            if server_ip not in self._commands:
                self._commands[server_ip] = {"server": [], "client": []}
            client = traffic.get_client()
            client_ip = client.get_ip()
            if client_ip not in self._commands:
                self._commands[client_ip] = {"server": [], "client": []}
            for i in range(traffic.get_process_num()):
                port = self._next_port()
                # Set up server first
                server_numa_node = server.get_numa()
                server_cmd = "numactl -N {} -m {} {} {} {} --server --port={} --use_cuda={} --tos=105 --share_mr --gpu_id=0 2>/dev/null &".format(
                    server_numa_node, server_numa_node,
                    self._binary, server.to_cmd(), traffic.to_cmd(),
                    port, bool(server._use_gpu))
                self._commands[server_ip]["server"].append(server_cmd)
                # Then, the client.
                client_numa_node = client.get_numa()
                client_cmd = "numactl -N {} -m {} {} {} {} --connect={} --port={} --use_cuda={} --tos=105  --share_mr --gpu_id=0 --run_infinitely 2>/dev/null &".format(
                    client_numa_node, client_numa_node,
                    self._binary, client.to_cmd(), traffic.to_cmd(),
                    server_ip, port, bool(client._use_gpu))
                self._commands[client_ip]["client"].append(client_cmd)
        return self._commands

    def gen_scripts(self):
        path = self._scripts_path
        ips = list(self._commands.keys())
        for ip in ips:
            with open(path + "{}_server.sh".format(ip), "w") as f:
                for cmd in self._commands[ip]["server"]:
                    f.write(cmd + "\n")
            with open(path + "{}_client.sh".format(ip), "w") as f:
                for cmd in self._commands[ip]["client"]:
                    f.write(cmd + "\n")
        return

    def log_scripts(self, point, path: str):
        # Re-translate on the same ports the measured run used, so the
        # reproduce script is a faithful replay rather than a fresh point.
        self.translate(point, base_port=self._base_port)
        ips = list(self._commands.keys())
        if not path.endswith(".sh"):
            path += ".sh"
        with open(path, "w") as f:
            for ip in ips:
                for cmd in self._commands[ip]["server"]:
                    f.write(
                        "ssh {}@{} -n -f \"{}\"".format(self._ip_to_host[ip], ip, cmd) + "\n")
                f.write("sleep 1\n")
            for ip in ips:
                for cmd in self._commands[ip]["client"]:
                    f.write(
                        "ssh {}@{} -n -f \"{}\"".format(self._ip_to_host[ip], ip, cmd) + "\n")
                f.write("sleep 1\n")
        self.clean()

    def save_err_scripts(self):
        ips = list(self._commands.keys())
        cmd = "mkdir -p {}/err_scripts/".format(self._scripts_path)
        subprocess.check_output(cmd, shell=True)
        for ip in ips:
            cmd = "mv {}/{}_server.sh {}/err_scripts/".format(
                self._scripts_path, ip, self._scripts_path)
            subprocess.check_output(cmd, shell=True)
            cmd = "mv {}/{}_client.sh {}/err_scripts/".format(
                self._scripts_path, ip, self._scripts_path)
            subprocess.check_output(cmd, shell=True)
        return

    def run_scripts(self):
        ips = list(self._commands.keys())
        for ip in ips:
            # scp /tmp/ip_server.sh
            cmd = ["scp", "{}{}_server.sh".format(self._scripts_path, ip), "{}{}_client.sh".format(self._scripts_path, ip),
                   "{}@{}:/tmp/".format(self._ip_to_host[ip], ip)]
            try:
                subprocess.check_output(cmd)
            except Exception as e:
                print(e)
                return -1
            setup_cmd = ["ssh", "-n", "-f", "{}@{}".format(self._ip_to_host[ip], ip),
                         "bash /tmp/{}_server.sh".format(ip)]
            try:
                subprocess.run(setup_cmd, stdout=subprocess.DEVNULL)
            except Exception as e:
                print(e)
                return -1
        # We have copied the scripts to all hosts and have set up servers.
        # Now we only need to set up clients
        for ip in ips:
            cmd = ["ssh", "-n", "-f", "{}@{}".format(self._ip_to_host[ip], ip),
                   "bash /tmp/{}_client.sh".format(ip)]
            try:
                subprocess.run(cmd, stdout=subprocess.DEVNULL)
            except Exception as e:
                print(e)
                return -1
        return 0

    def set_up_traffic(self, point):
        # return 0 means success
        self.translate(point)
        self.gen_scripts()
        self.run_scripts()
        n = self.check_run(point.get_total_qps())
        if (n != 0):
            self.save_err_scripts()
            return -1
        return 0

    def clean(self):
        # NOTE: upstream reset _global_port to 3000 here, so every point reused
        # the same low ports and raced the previous point's TIME_WAIT sockets.
        # The counter is now monotonic; only the command list is cleared.
        self._commands.clear()

    def killall(self):
        # `killall <abs-path>` (upstream) does not match a process whose comm is
        # just "collie_engine", so leftovers survived between points.  pkill -f
        # matches the full command line instead.  The pattern is bracketed so
        # that the remote `bash -c` running pkill does not match itself and
        # tear down the ssh session before pkill reports its status.
        ips = self._ip_to_host.keys()
        clean_cmds = []
        for ip in ips:
            target = "{}@{}".format(self._ip_to_host[ip], ip)
            # TERM first, then a KILL sweep for anything wedged in the kernel.
            remote = ("pkill -f '[c]ollie_engine'; sleep 1; "
                      "pkill -9 -f '[c]ollie_engine'; true")
            cmd = ["ssh", target, remote]
            try:
                subprocess.run(cmd, stdout=subprocess.DEVNULL,
                               stderr=subprocess.DEVNULL)
            except Exception as e:
                print(e)
                return -1
            clean_cmds.append(cmd)
        with open(self._scripts_path + "clean.sh", "w") as f:
            for cmd in clean_cmds:
                f.write(" ".join(cmd) + "\n")
        return 0

    def clean_process(self):
        # return 0 means success
        if self.killall():
            print("Error when killing all engines")
            return -1
        n = self.check_run(0)
        if (n != 0):
            print("Checking Killall failed.")
            return -1
        self.clean()
        return 0
